Waedist/Models/Category.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Waedist.Models
{
    public partial class Category
    {
        public Category()
        {
            Stores = new HashSet<Store>();
        }

        public decimal Categoryid { get; set; }
        public string Categoryname { get; set; }
        public string Pic { get; set; }

        public virtual ICollection<Store> Stores { get; set; }
    }
}

Waedist/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Waedist.Models;

namespace Waedist.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _iwebHostEnvirounment;
    
        public CategoriesController(ModelContext context , IWebHostEnvironment iwebHostEnvirounment)
        {
            _context = context;
            _iwebHostEnvirounment = iwebHostEnvirounment;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            return View(await _context.Categories.ToListAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Index(string? category)
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");

            var cat = await _context.Categories.ToListAsync();
            if (category != null)
            {
                var result = cat.Where(x => x.Categoryname.ToUpper().Contains(category.ToUpper()));
                return View(result);
            }
            return View(cat);
        }
        public async Task<IActionResult> UserIndex(  )
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            return View(await _context.Categories.ToListAsync());
        }




    
        [HttpPost]
        public async Task<IActionResult> UserIndex(string? category)
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
           ViewBag.UserId = HttpContext.Session.GetInt32("UserId");

            var cat = await _context.Categories.ToListAsync();
            if (category != null)
            {
                var result = cat.Where(x => x.Categoryname.ToUpper().Contains(category.ToUpper()));
                return View(result);
            }
            return View(cat);
        }










        public async Task<IActionResult> AdminIndex()
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            return View(await _context.Categories.ToListAsync());
        }

        public async Task<IActionResult> ManageCategories()
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            return View(await _context.Categories.ToListAsync());
        }
    

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Categoryid == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            ViewBag.Categries = _context.Categories.ToList();
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Categoryid,Categoryname,Pic")] Category category , IFormFile img)
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            if (ModelState.IsValid)
            {
                if (img != null)
                {

                    string wwwroot = _iwebHostEnvirounment.WebRootPath;
                    string filename = Guid.NewGuid() + "_" + img.FileName;
                    string path = Path.Combine(wwwroot + "/Images/Category/", filename);

                    using (var filestream = new FileStream(path, FileMode.Create))
                    {


                        img.CopyTo(filestream);
                        category.Pic = filename;
                        _context.Add(category);
                        await _context.SaveChangesAsync();
                    }
                 
                    return RedirectToAction(nameof(Index));

                }

            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(decimal? id  )
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");

Waedist/Views/Categories/AdminIndex.cshtml
@model IEnumerable<Waedist.Models.Category>

@{
    ViewData["Title"] = "Dashboard| Categories";
    Layout = "~/Views/Shared/_AdminDashboardLayout.cshtml";
}

<div class="col-xl-12 pe-xl-2">
    <div class="card mb-3 h-lg-100">
        <div class="card-header">
            <div class="row flex-between-end">
                <div class="col-auto align-self-center">
                    <h5 class="mb-0" data-anchor="data-anchor" id="basic-example">Categories<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="#" style="padding-left: 0.375em;"></a></h5>
                </div>
                <div class="col-auto ms-auto">
                    <div class="nav nav-pills nav-pills-falcon flex-grow-1" role="tablist">
                        <a class="btn btn-sm active" asp-controller="Categories" asp-action="Create">Create New</a>
                    </div>
                </div>


            </div>
        </div>
        <div class="card-body bg-light">
            <div class="tab-content">
                <div class="row  " role="tabpanel" aria-labelledby="tab-dom-14c3402d-e89a-4345-96a2-6d6bfd4d40ed" id="dom-14c3402d-e89a-4345-96a2-6d6bfd4d40ed">
                    @foreach (var c in Model)
                    {
                        <div class=" card overflow-hidden" style="width: 20rem; margin-left:65px; margin-top:30px ">
                            <div class="card-img-top"><img style="height:400px ; margin:5px; padding:5px" class="img-fluid" src="@Url.Content("~/Images/Category/"+ c.Pic)" alt="Card image cap"></div>
                            <div class="card-body">
                                <h5 class="card-title">@c.Categoryname</h5>
                                <a style="background-color: #eeb7c3; margin-left:5px; border-color: #eeb7c3 ; border-radius:20px;" class="btn btn-primary btn-sm" asp-controller="Categories" asp-action="Edit" asp-route-id="@c.Categoryid">Edit Product</a>
                                <a style="margin-top: 7px;margin-left:5px; background-color: #eeb7c3; border-color: #eeb7c3 ; border-radius:20px; color:brown " asp-controller="Categories" asp-action="Delete" asp-route-id="@c.Categoryid" class=" btn btn-primary btn-sm">Delete Product</a>
                            </div>
                        </div>

                    }

                </div>
            </div>
        </div>
    </div>
</div>



@*<h1>AdminIndex</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Categoryname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pic)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoryname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pic)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Categoryid">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Categoryid">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Categoryid">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>*@

Waedist/Views/Categories/Create.cshtml
@model Waedist.Models.Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminDashboardLayout.cshtml";
}







<div class="card-body overflow-hidden">

    <p>

    </p>
    <div class="row mx-n4 ">
        <div style="width:66%;margin:auto; margin-top:80px  "  class="col-8 row-cols-8 p-1">
            <div style="height: 400px; " class=" card ">
                <div class="card-header">
                    <h5 class="mb-0">Craete Categorey</h5>
                </div>
                <div style="margin-bottom: 20px; margin-left: 437px; height: 0px; " class="nav nav-pills nav-pills-falcon flex-grow-1" role="tablist">
                    <a class="btn btn-sm active" asp-controller="Categories" asp-action="Index">Back to the List</a>
                </div>
                <div id="Edit" class="card-body bg-light pb-0">
                    <div class="collapse show" id="experience-form">
                        <form asp-action="Create" enctype="multipart/form-data" method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>


                            <div class="col-9 col-sm-7 mb-3">
                                <label style="margin-right:70px" class="control-label" asp-for="Categoryname">Category Name</label>

                                <input style="width:535px" asp-for="Categoryname" class="form-control form-control-sm" type="text">
                            </div>

                            <div class="form-group">
                                <label for="img" class="control-label"></label>
                                <input type="file" accept="image/*" name="img" id="img" class="form-control" />
                            </div>

                            <div class="col-9 col-sm-7 offset-3">
                                <button style=" margin-left:270px; margin-top: 20px; background-color: #eeb0bc; border-color: #eeb0bc; border-radius: 20px; " class="btn btn-primary rounded-sm" type="submit" value="Create">Create</button>
                            </div>
                        </form>
                        <div class="border-dashed-bottom my-4"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>







    @*<h1>Create</h1>

    <h4>Category</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Categoryname" class="control-label"></label>
                    <input asp-for="Categoryname" class="form-control" />
                    <span asp-validation-for="Categoryname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="img" class="control-label"></label>
                    <input  type="file" accept="image/*" name="img" id="img" class="form-control" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>*@

Waedist/Views/Categories/Delete.cshtml
@model Waedist.Models.Category

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_AdminDashboardLayout.cshtml";
}


<h3 class="text-danger">Are you sure you want to delete this Category?</h3>
<div>
    
    <hr />
    <dl class="row">
      
        <dd style="font-size:larger; font-weight:bold" class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoryname)
        </dd>
       
        <dd class="col-sm-10">
            <img style="height:400px ; margin:5px; padding:5px" class="img-fluid" src="@Url.Content("~/Images/Category/"+ Model.Pic)" alt="Card image cap">
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Categoryid" />
        <input style="border-radius:20px;" type="submit" value="Delete" class="btn btn-danger" /> |
        <a style="color: #eeb7c3" asp-controller="Categories" asp-action="Index">Back to List</a>
    </form>
</div>

Waedist/Views/Categories/Details.cshtml
@model Waedist.Models.Category

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoryname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoryname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pic)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Categoryid">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Waedist/Views/Categories/Edit.cshtml
@model Waedist.Models.Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminDashboardLayout.cshtml";
}




<div class="card-body overflow-hidden">

    <p>

    </p>
    <div class="row mx-n4 ">

        <div class="col-4 row-cols-8 p-xl-2">

            @foreach (var c in ViewBag.Categries)
            {
                if (c.Categoryid == ViewBag.CatId)
                {
                    <img style="margin-right:0px ;  height:400px" class="img-fluid rounded" src="@Url.Content("~/Images/Category/" + c.Pic)" alt="">
                }
            }
        </div>
        <div class="col-8 row-cols-8 p-1">
            <div style="height:400px" class=" card ">
                <div class="card-header">
                    <h5 class="mb-0">Edit Categorey</h5>
                </div>
                <div style="margin-bottom: 20px; margin-left: 437px; height: 0px; " class="nav nav-pills nav-pills-falcon flex-grow-1" role="tablist">
                    <a class="btn btn-sm active" asp-controller="Categories" asp-action="Index">Back to the List</a>
                </div>
                <div id="Edit" class="card-body bg-light pb-0">
                    <div class="collapse show" id="experience-form">
                        <form asp-controller="Categories" asp-action="Edit" enctype="multipart/form-data" method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Categoryid" />
                            <input type="hidden" asp-for="Pic" />


                            <div class="col-9 col-sm-7 mb-3">
                                <label style="margin-right:70px" class="control-label" asp-for="Categoryname">Category Name</label>

                                <input style="width:535px" asp-for="Categoryname" class="form-control form-control-sm" type="text">
                            </div>

                            <div class="form-group">
                                <label for="img" class="control-label">Header Image</label>
                                <input type="file" accept="image/*" name="img" id="img" class="form-control" />
                            </div>

                            <div class="col-9 col-sm-7 offset-3">
                                <button style=" margin-left:270px; margin-top: 10px; background-color: #eeb0bc; border-color: #eeb0bc; border-radius: 20px; " class="btn btn-primary rounded-sm" type="submit">Update </button>
                            </div>
                        </form>
                        <div class="border-dashed-bottom my-4"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>






















@*<h1>Edit</h1>

    <h4>Category</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Categoryid" />
                <input type="hidden" asp-for="Pic" />

                <div class="form-group">
                    <label asp-for="Categoryname" class="control-label"></label>
                    <input asp-for="Categoryname" class="form-control" />
                    <span asp-validation-for="Categoryname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="img" class="control-label"></label>
                    <input type="file" accept="image/*" name="img" id="img" class="form-control" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>*@

Waedist/Views/Categories/ManageCategories.cshtml
@model IEnumerable<Waedist.Models.Category>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminDashboardLayout.cshtml";
}










<div class="container">
    <div class="row g-3 mb-3">
        <div class="col-md-6 col-xxl-3">
            <div class="">

                <p>
                    <a asp-action="Create">Create New</a>
                </p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Categoryname)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Pic)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Categoryname)
                                </td>
                                <td>


                                    <img src="@Url.Content("~/Images/Store"+ item.Pic)" style="height:250px" ; width:"250px;" />

                                </td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@item.Categoryid">Edit</a> |
                                    <a asp-action="Details" asp-route-id="@item.Categoryid">Details</a> |
                                    <a asp-action="Delete" asp-route-id="@item.Categoryid">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>