Waedist/Models/Useraccount.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Waedist.Models
{
    public partial class Useraccount
    {
        public Useraccount()
        {
            Orderrs = new HashSet<Orderr>();
            Payments = new HashSet<Payment>();
            Testmoninals = new HashSet<Testmoninal>();
        }

        public decimal Userid { get; set; }
        public string Fullname { get; set; }
        public decimal? Phonenumber { get; set; }
        public string Pic { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public decimal? Roleid { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Orderr> Orderrs { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Testmoninal> Testmoninals { get; set; }
    }
}

Waedist/Controllers/UseraccountsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Waedist.Models;

namespace Waedist.Controllers
{
    public class UseraccountsController : Controller
    {
        private readonly ModelContext _context;
        private readonly IWebHostEnvironment _iwebHostEnvirounment;

        public UseraccountsController(ModelContext context, IWebHostEnvironment iwebHostEnvirounment)
        {
            _context = context;
            _iwebHostEnvirounment = iwebHostEnvirounment;
        }

        // GET: Useraccounts
        public async Task<IActionResult> Index()
        {
            ViewBag.Users = _context.Useraccounts.ToList();
            var modelContext = _context.Useraccounts.Include(u => u.Role);
            return View(await modelContext.ToListAsync());
        }

        // GET: Useraccounts/Details/5
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var useraccount = await _context.Useraccounts
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Userid == id);
            if (useraccount == null)
            {
                return NotFound();
            }

            return View(useraccount);
        }

        // GET: Useraccounts/Create
        public IActionResult Create()
        {
            ViewData["Roleid"] = new SelectList(_context.Roles, "Roleid", "Roleid");
            return View();
        }

        // POST: Useraccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Userid,Fullname,Phonenumber,Pic,Email,Password,Roleid")] Useraccount useraccount, IFormFile img)
        {
            if (ModelState.IsValid)
            {
                if (img != null)
                {

                    string wwwroot = _iwebHostEnvirounment.WebRootPath;
                    string filename = Guid.NewGuid() + "_" + img.FileName;
                    string path = Path.Combine(wwwroot + "/Images/", filename);

                    using (var filestream = new FileStream(path, FileMode.Create))
                    {

                        img.CopyTo(filestream);
                        useraccount.Pic = filename;
                        useraccount.Roleid = 2;
                        _context.Add(useraccount);
                        await _context.SaveChangesAsync();

                    }


                }

                return RedirectToAction(nameof(Index));
            }
            ViewData["Roleid"] = new SelectList(_context.Roles, "Roleid", "Roleid", useraccount.Roleid);
            return View(useraccount);
        }

        // GET: Useraccounts/Edit/5
        public async Task<IActionResult> Edit(decimal? id)
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.flag = HttpContext.Session.GetInt32("IncorrectPass");

            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            ViewBag.Users = _context.Useraccounts.ToList();

            if (id == null)
            {
                return NotFound();
            }

            var useraccount = await _context.Useraccounts.FindAsync(id);
            if (useraccount == null)
            {
                return NotFound();
            }
            ViewData["Roleid"] = new SelectList(_context.Roles, "Roleid", "Roleid", useraccount.Roleid);
            return View(useraccount);
        }

        // POST: Useraccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(decimal id, [Bind("Userid,Fullname,Phonenumber,Pic,Email,Password,Roleid")] Useraccount useraccount, IFormFile img, string? Old, string? password)
        {
            if (password != null && Old != null)
            {
                HttpContext.Session.SetInt32("IncorrectPass", 2);

                var user = AdminPass(id, Old, password);
                return RedirectToAction(nameof(Edit));
                return View(user);
            }


            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");

            if (id != useraccount.Userid)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {



                HttpContext.Session.SetInt32("IncorrectPass", 2);



                try
                {
                    HttpContext.Session.SetInt32("IncorrectPass", 2);

                    if (img != null)
                    {
                        string wwwroot = _iwebHostEnvirounment.WebRootPath;
                        string filename = Guid.NewGuid() + "_" + img.FileName;
                        string path = Path.Combine(wwwroot + "/Images/", filename);
                        using (var filestream = new FileStream(path, FileMode.Create))
                        {
                            img.CopyTo(filestream);
                            useraccount.Pic = filename;
                        }

               
                        HttpContext.Session.SetInt32("IncorrectPass", 2);

                    }

                    _context.Update(useraccount);
                    await _context.SaveChangesAsync();
                    ViewBag.Users = _context.Useraccounts.ToList();

                    ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
                    ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UseraccountExists(useraccount.Userid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            

                return RedirectToAction(nameof(Edit));



            }

            ViewData["Roleid"] = new SelectList(_context.Roles, "Roleid", "Roleid", useraccount.Roleid);
            return View(useraccount);

        }
        public async Task<IActionResult> AdminPass(decimal id, string Old, string password)
        {
            ViewBag.Users = _context.Useraccounts.ToList();
            var pass = _context.Useraccounts.Where(x => x.Userid == id).SingleOrDefault();


            if (pass.Password == Old)
            {
                HttpContext.Session.SetInt32("IncorrectPass", 0);
                ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
                ViewBag.Users = _context.Useraccounts.ToList();


                pass.Password = password;
                _context.Update(pass);
                await _context.SaveChangesAsync();


            }
            else if (pass.Password != Old)
            {
                HttpContext.Session.SetInt32("IncorrectPass", 1);
                ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
                ViewBag.Users = _context.Useraccounts.ToList();



            }
            await _context.SaveChangesAsync();




            ViewData["Roleid"] = new SelectList(_context.Roles, "Roleid", "Roleid", pass.Roleid);
            return View(pass);

        }








        public async Task<IActionResult> UserProfile(decimal? id)
        {
            ViewBag.Roleid = HttpContext.Session.GetInt32("Roleid");
            ViewBag.Logged = HttpContext.Session.GetInt32("AlredyLogged");
            ViewBag.flag = HttpContext.Session.GetInt32("IncorrectPass");

            ViewBag.Users = _context.Useraccounts.ToList();

            ViewBag.Adminid = HttpContext.Session.GetInt32("AdminId");
            ViewBag.AdminN = HttpContext.Session.GetString("AdminName");
            ViewBag.AdminImg = HttpContext.Session.GetString("Image");
            ViewBag.UserName = HttpContext.Session.GetString("FullName");
            ViewBag.UserEmail = HttpContext.Session.GetString("UserEmail");
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            ViewBag.Users = _context.Useraccounts.ToList();

            if (id == null)
            {
                return NotFound();
            }

            var useraccount = await _context.Useraccounts.FindAsync(id);
            if (useraccount == null)
            {
                return NotFound();
            }
            ViewData["Roleid"] = new SelectList(_context.Roles, "Roleid", "Roleid", useraccount.Roleid);
            return View(useraccount);
        }

        // POST: Useraccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

Waedist/Views/Useraccounts/Create.cshtml
@model Waedist.Models.Useraccount

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Useraccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Fullname" class="control-label"></label>
                <input asp-for="Fullname" class="form-control" />
                <span asp-validation-for="Fullname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phonenumber" class="control-label"></label>
                <input asp-for="Phonenumber" class="form-control" />
                <span asp-validation-for="Phonenumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="img" class="control-label"></label>
                <input type="file" accept="image/*" name="img" id="img" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Waedist/Views/Useraccounts/Delete.cshtml
@model Waedist.Models.Useraccount

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Useraccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fullname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phonenumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phonenumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role.Roleid)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Userid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Waedist/Views/Useraccounts/Details.cshtml
@model Waedist.Models.Useraccount

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Useraccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fullname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phonenumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phonenumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Role.Roleid)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Userid">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Waedist/Views/Useraccounts/Index.cshtml
@model IEnumerable<Waedist.Models.Useraccount>

@{
    ViewData["Title"] = "Index";
    Layout = "_AdminDashboardLayout";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fullname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phonenumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Role)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Fullname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phonenumber)
                </td>
                <td>
                    <img src="@Url.Content("~/Images/"+ item.Pic)" style="height:250px ; width:250px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Role.Roleid)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Userid">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Userid">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Userid">Delete</a>
                </td>
            </tr>








        }
    </tbody>
</table>











































@{
    Layout = "_AdminDashboardLayout";
}
































@*<!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Create</title>
    </head>
    <body>

    <h4>Productstore</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Productid" class="control-label"></label>
                    <select asp-for="Productid" class ="form-control" asp-items="ViewBag.Productid"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Storeid" class="control-label"></label>
                    <select asp-for="Storeid" class ="form-control" asp-items="ViewBag.Storeid"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
    </body>
    </html>*@

Waedist/Views/Useraccounts/UserProfile.cshtml
@model Waedist.Models.Useraccount

@{
    ViewData["Title"] = "My Profile";
    Layout = "_UserDashboardLayout";
}
@*
    <div class="row g-0">
        <div class="col-lg-8 pe-lg-2">
            <div class="card mb-3">
                <div class="card-header">
                    <h5 class="mb-0">Profile Settings</h5>
                </div>
                <div class="card-body bg-light">
                    <form class="row g-3" asp-action="Edit" method="post" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="col-lg-12">
                            <label asp-for="Fullname" class="form-label">Full Name</label>
                            <input asp-for="Fullname" class="form-control" id="Fullname" name="Fullname" type="text">
                            <span asp-validation-for="Fullname" class="text-danger"></span>

                        </div>
                        <div class="col-lg-6">
                            <label asp-for="Phonenumber" class="form-label" >Phone</label>
                            <input asp-for="Phonenumber" class="form-control"  name="Phonenumber" id="Phonenumber" type="text">
                            <span asp-validation-for="Phonenumber" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <label for="img" class="control-label"></label>
                            <input type="file" accept="image/*" name="img" id="img" class="form-control" />
                        </div>
                        <div class="col-lg-6">
                            <label asp-for="Email" class="form-label">Email</label>
                            <input asp-for="Email" class="form-control" name="Email" id="Email" type="text">
                            <span asp-validation-for="Email" class="text-danger"></span>

                        </div>
                        <div class="form-group">
                            <label asp-for="Password"  class="form-label"></label>
                            <input asp-for="Password" name="Password" id="Password" class="form-label" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>

                        <input type="hidden" asp-for="Roleid" />



                        <div class="col-12 d-flex justify-content-end">
                            <button class="btn btn-primary" value="Save" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



*@



<div class="row">
    <div class="col-12">
        <div style=" background-color: #FEFDFD " class="card mb-3 btn-reveal-trigger">
            <div style="background-color: #FEFDFD; margin-bottom: 5.5rem !important; min-height: 12vh !important; " class="card-header position-relative min-vh-25 mb-8">
                <div style="height:250px" class="cover-image">
                    <!--/.bg-holder-->
                    <video class="bg-video" autoplay="autoplay" loop="loop" muted="muted" playsinline="playsinline">
                        <source src="~/DashboardStatics/video/X2Download.com-Clouds%20in%20the%20pink%20sky%20at%20sunset%20(A).mp4" type="video/mp4">
                        <source src="~/DashboardStatics/video/X2Download.com-Clouds%20in%20the%20pink%20sky%20at%20sunset%20(A).webm" type="video/webm">
                    </video>
                </div>


                    <div class="avatar avatar-5xl avatar-profile shadow-sm img-thumbnail rounded-circle">
                        <div class="h-100 w-100 rounded-circle overflow-hidden position-relative">
                          
                               
                                    <img src="@Url.Content("~/Images/" + Model.Pic)" width="200" alt="" data-dz-thumbnail="data-dz-thumbnail">
                          
                            

                              
                      
                         </div>
                    <div class="col-12 position-absolute justify-content-end">
                    
                    
                    
                    
                    </div>
              


                 </div>
            </div>
        </div>
    </div>

</div>

<div class="row g-0">

    <div class="col-12 pe-lg-2">
        <div class="card mb-3">
            <div style=" background-color: #FEFDFD " class="card-header">
                <h5 class="mb-0">Profile Settings</h5>
            </div>
            <div class="card-body bg-light">
                <form asp-controller="Useraccounts" asp-action="UserProfile" enctype="multipart/form-data" class="row g-3">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Pic" />


                    <input type="hidden" asp-for="Userid" />
                    <div class="col-lg-12">
                        <label asp-for="Fullname" class="form-label">Full Name</label>
                        <input asp-for="Fullname" class="form-control" type="text">
                        <span asp-validation-for="Fullname" class="text-danger"></span>

                    </div>
                    <div class="col-lg-6">
                        <label asp-for="Email" class="form-label">Email</label>
                        <input asp-for="Email" class="form-control" type="email">
                        <span asp-validation-for="Fullname" class="text-danger"></span>

                    </div>
                    <div class="col-lg-6">
                        <label asp-for="Phonenumber" class="form-label">Phone</label>
                        <input asp-for="Phonenumber" class="form-control" type="number">
                        <span asp-validation-for="Phonenumber" class="text-danger"></span>

                    </div>
                    <div class="col-lg-12">
                        <label for="img" class="form-label">Profile Picture</label>
                        <input type="file" accept="image/*" name="img" id="img" class="form-control" />
                    </div>


                    <input type="hidden" asp-for="Password" />
                    <input type="hidden" asp-for="Roleid" />


                    <div class="col-12 d-flex justify-content-end">
                        <button style=" background-color: #eeb0bc; border-color: #eeb0bc; border-radius: 20px; " class="btn btn-primary rounded-sm" type="submit">Update </button>
                    </div>

                </form>
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="mb-0">Change Password</h5>
            </div>
            <div class="card-body bg-light">
                <form asp-controller="Useraccounts" asp-action="UserProfile"  enctype="multipart/form-data" class="row g-3">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Pic" />
                    <input type="hidden" asp-for="Email" />
                    <input type="hidden" asp-for="Phonenumber" />
                    <input type="hidden" asp-for="Fullname" />
                    <input type="hidden" asp-for="Roleid" />
                    <input type="hidden" asp-for="Userid" />

                    <div class="mb-3">

                        @if (ViewBag.flag == 0)
                        {
                            <p><span style="font-size:smaller;color:green">Password changed</span></p>
                        }
                        @if (ViewBag.flag == 1)
                        {
                            <p><span style="font-size:smaller;color:red">Old password is incorrect </span></p>
                        }
                        <label name="Old" class="form-label" for="Old">Old Password</label>
                        <input name="Old" class="form-control" type="password">
                    </div>
                    <div class="mb-3">
                        <label name="Password" class="form-label" for="Password">New Password</label>
                        <input name="password" class="form-control" type="password">
                    </div>
                    <button style=" background-color: #eeb0bc; border-color: #eeb0bc; border-radius:20px;" class="btn btn-primary d-block w-100" type="submit">Update Password </button>
                </form>
            </div>
        </div>
    </div>

</div>